version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: app_local_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app_local_network

volumes:
  esdata:

networks:
  app_local_network: