spring:
  profiles:
    include: base, local_db
a:
  local
---
spring:
  profiles: base
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    username: root
    password: kpwd
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: WARN
    spring: INFO
    app: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
a:
  base
---
spring:
  profiles: local_db
  flyway:
    locations: classpath:db/migration
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3307/local_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
a:
  local_db
---
spring:
  profiles: mem_db
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    url: jdbc:h2:~/mem_db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
a:
  mem_db
