spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
logging:
  level:
    org:
      springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"