spring:
  flyway:
    locations: classpath:db/migration
    enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/mock_DB;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
