spring:
  profiles:
    include: base, local_db
a:
  local
---
spring:
  profiles: base
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    username: root
    password: kpwd
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
a:
  base
---
spring:
  profiles: local_db
  flyway:
    locations: classpath:db/migration
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/local_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
a:
  local_db
---
spring:
  profiles: mem_db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/mem_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
a:
  mem_db
