spring:
  profiles:
    include: base, h2_db
a:
  local
---
spring:
  profiles: base
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    username: root
    password: kpwd
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: WARN
    spring: INFO
    app: DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
a:
  base
---
spring:
  profiles: local_db
  flyway:
    locations: classpath:db/migration
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    url: jdbc:mysql://${db.containerId:localhost}:3307/app_local_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
a:
  local_db
---
spring:
  profiles: local_db_hibernate
  flyway:
    locations: classpath:db/migration
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    url: jdbc:mysql://${db.containerId:localhost}:3307/app_local_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
a:
  local_db_hibernate
---
spring:
  profiles: h2_db
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  datasource:
    url: jdbc:h2:~/h2_db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
a:
  h2_db
